//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class path
    {
        public int id { get; set; }
        public int number_order { get; set; }
        public string list { get; set; }
        public System.DateTime order_date { get; set; }
        public System.DateTime end_delivery { get; set; }
        public int pick_up_point { get; set; }
        public string FIO { get; set; }
        public int code { get; set; }
        public int order_status { get; set; }
        public int users { get; set; }
        public Nullable<int> id_produkt { get; set; }
    
        public virtual point point { get; set; }
        public virtual status status { get; set; }
        public virtual users users1 { get; set; }
    }
}
