//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Лист3_
    {
        public int id { get; set; }
        public Nullable<int> id_catekoria { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<int> quantity { get; set; }
        public string discription { get; set; }
        public string image { get; set; }
        public string CurrentPhoto
{
    get
    {
        if (String.IsNullOrEmpty(image) || String.IsNullOrWhiteSpace(image))
        {
            return "/images/picture.png";
        }
        else
        {
            return "/images/" + image;
        }
    }
}
        
    }
}
